### ISSUE TITLE
Is there any way I can get the Critical Services using this API? For example, I want to retrieve the host down alerts as soon as a server goes down, or if Memory goes high on some server and check shows it critical I want to retreive it using python.

### ISSUE THREAD

**Issue by Yagyansh** [brennerm/check-mk-web-api#18]

**Comment by brennerm** [comment]
Hi @Yagyansh, unfortunately the Checkmk Web API does not support this feature.

You can check the [command reference](https://checkmk.com/cms_web_api_references.html) for future additions. I will add support for new endpoints to this library asap.
