### ISSUE TITLE
New release with fixes in `master`

### ISSUE THREAD

**Issue by marshallmcdonnell** [brennerm/check-mk-web-api#21]
Hi @brennerm,

Awesome project! Thanks so much, we are adding auto registering new hosts into our CheckMK monitoring this morning and your package saved a ton of time! :+1: 

I had a quick question, when will you be releasing the new release (ie 1.4 is out at time of this post and in PyPi so asking about 1.5). Specifically, lost some time this morning on the fix in this commit: https://github.com/brennerm/check-mk-web-api/commit/ebd68c5b33da2d1edbce363fcbc5f0fb839c9690. Would help with installs from `pip` versus needing to install from source right now off of `master` with set commit. 

Again, really appreciate your work! Thanks!

Best,
Marshall

**Comment by brennerm** [comment]
Hey @marshallmcdonnell, appreciate your feedback!

Version 1.5 including the fixes has just been released.

**Comment by marshallmcdonnell** [comment]
Thanks @brennerm, greatly appreciated!
