### ISSUE TITLE
How to specify refresh type?

### ISSUE THREAD

**Issue by jake9050** [brennerm/check-mk-web-api#3]
Hi, 

First of all thanks for this api wrapper!

I see that you define this:

```
    class DiscoverMode(enum.Enum):
        """
        new - Only discover new services
        remove - Remove exceeding services
        fixall - Remove exceeding services and discover new services
        refresh - Start from scratch
        """
        NEW = 'new'
        REMOVE = 'remove'
        FIXALL = 'fixall'
        REFRESH = 'refresh'
```

And then you set the discovery request to NEW:

` discover_services(self, hostname: str, mode: DiscoverMode=DiscoverMode.NEW):`

Can this be overridden to the other types? I have tried various ways of doing this:

```
api.discover_services(host,  DiscoverMode='REFRESH')
'str' object has no attribute 'value'
api.discover_services(h, 'mode:REFRESH')
'str' object has no attribute 'value'
api.discover_services(h, mode.REFRESH)
name 'mode' is not defined
api.discover_services(h, DiscoverMode.REFRESH)
name 'DiscoverMode' is not defined
```

I am not very proficient in python yet, but if you could give me some pointers i should be able to figure out what to change.

**Comment by brennerm** [comment]
Hey @jake9050,

make sure to have the _WebApi_ class imported from the _check_mk_web_api_ module.
```python
from check_mk_web_api import WebApi
```
Afterwards you have access to the _DiscoverMode_ enum.
```python
api.discover_services(h, WebApi.DiscoverMode.FIXALL)
```

**Comment by jake9050** [comment]
Thanks for the swift response @brennerm , now i can make it do what i want.
