### ISSUE TITLE
Default alert rules export, no API

### ISSUE THREAD

**Issue by ryanlll3** [brennerm/check-mk-web-api#32]
I need to get the list of activated alerting rules, service names which are default or autodicovered.
But I see I couldn't get the list of default thresholds, service names.

Do you think you could help or guide?

Ryan

**Comment by brennerm** [comment]
Hey @ryanlll3, [here](https://checkmk.com/cms_web_api_references.html) you can find a list of all currently supported commands. As you can see there's no way to export alert rules at all. So this is not possible with the current web API.

It may be possible with the new REST API comming with 2.0, which will be adopted by this project (#31) as well.
