### ISSUE TITLE
get_all_sites missing?

### ISSUE THREAD

**Issue by dblviking** [brennerm/check-mk-web-api#33]
As per this https://checkmk.com/check_mk-werks.php?werk_id=6689

get_all_sites works via curl but I don't see that interface in your release

Thank you!

**Comment by brennerm** [comment]
I confirmed that they work but they aren't part of the [official docs](https://checkmk.com/cms_web_api_references.html). Hence I [asked checkmk](https://twitter.com/__brennerm/status/1335196167668441088) whether they can be considered stable. Let's see what they say.

**Comment by dblviking** [comment]
In the meantime, is there a way to fetch all sites using your module? Cheers

**Comment by brennerm** [comment]
Yes, you can use `WebApi(...). make_request("get_all_sites")`

**Comment by dblviking** [comment]
It looks like it needs one more parameter:

```
  File "/usr/local/lib/python3.6/site-packages/check_mk_web_api/__init__.py", line 164, in make_request
    raise CheckMkWebApiException(result)
check_mk_web_api.exception.CheckMkWebApiException: Check_MK exception: This API call requires the parameter output_format=python

```

**Comment by dblviking** [comment]
> It looks like it needs one more parameter:
> 
> ```
>   File "/usr/local/lib/python3.6/site-packages/check_mk_web_api/__init__.py", line 164, in make_request
>     raise CheckMkWebApiException(result)
> check_mk_web_api.exception.CheckMkWebApiException: Check_MK exception: This API call requires the parameter output_format=python
> ```

Never mind! I didn't notice the parameters were in dict format. It's working :)

make_request("get_all_sites",query_params= { 'output_format': 'python'})

**Comment by brennerm** [comment]
Correct, forgot to add the `query_params`. So as you've guessed it's `make_request('get_all_sites', query_params={'output_format': 'python'})`
