### ISSUE TITLE
Very good tool

### ISSUE THREAD

**Issue by hoshang82** [brennerm/check-mk-web-api#5]
Hi all,
thank you so much for this web api tool its really very very helpful.
I have only a question, is there a way to not install the web-api ?
I want use it beside my other python files ?

thanks in advance

Best Regards
Neeloj

**Comment by brennerm** [comment]
Hi Neeloj,

Thanks for your appreciation.

To use the library without installing it you can just clone the repository and copy the check_mk_web_api folder next to your python script or adding it to your PYTHONPATH. Afterwards you can import it.

Not quite sure if this answers your question. If not just let me know and further explain your problem.
 
Cheers,
Max

**Comment by hoshang82** [comment]
Thank you so much Max:-) it works like a charm :-)
I hope you will add more features to this fantastic check_mk_web_api :-)
