### ISSUE TITLE
editing hosts

### ISSUE THREAD

**Issue by FlorianHeigl** [brennerm/check-mk-web-api#7]
Hi ;-)

So, one thing I had postponed a month back and just returned to:
* When I add a host, I can pass tags or a WATO folder.
* When I try to do an update, I get an error

```Check_MK Fehler: Unbekanntes Attribut: tags```

(same with folder)

I can imagine API-side issues updating folders (would love none though) but since I can't do even tags, it feels strange.

I've tried for a bit, sending back the same structure as one receives on get_host using update_host seems to not be possible.
Do you have any advice about modifying what's in the attributes dictionary of the API query?

My use case is manyfold, first I store a hash of the system's host tags and other stuff in the alias field, then I compare that value to see if any system has been updated in CMDB etc.
If yes, I want to apply the updates to the existing host.

For now I think I can work around by deleting the node, but if you got an example updating more than the ip I would be very curious.

**Comment by brennerm** [comment]
Hey @FlorianHeigl,
following the [Check_MK Web API command reference](https://mathias-kettner.com/cms_web_api_references.html#edit_host) it seems like the proper way would be use the same attribute name that you receive from the get_host endpoint.

As you already tried this I cannot think of another way to achieve the desired outcome.

Maybe you can contact the Check_MK support and ask if this is possible using the Web API.

**Comment by Yogibaer75** [comment]
Hi Max and Florian,

for the problem with the host update i found the following solution.
First create a dictionary with the desired tags inside - example
attributes = {'tag_nw_hersteller':'nw_cisco','tag_criticality': 'offline'}
And then make the following request
api.make_request('edit_host', data={'hostname': updatedhost, 'attributes': attributes})
This is working nicely in one of my bigger setups with automatic update the hosts from a CMDB.

**Comment by FlorianHeigl** [comment]
@Yogibaer75 Hi Andreas ;-)
Have you per chance also found a way to do bulk updates? I didn't care try yet, meaning I do a few thousand API calls ;-)

**Comment by brennerm** [comment]
Never heard of bulk operations using the API. Just loop through your hosts and update them using this library. That's what it's for. ;)

**Comment by Yogibaer75** [comment]
I have done these updates with over 1000 switches and had no problems with performance. It takes some time yes but it was working stable.
The only "bulk" operations are all the get_all things.

**Comment by brennerm** [comment]
@FlorianHeigl Have a look at [this](https://mathias-kettner.com/cms_web_api_references.html#Host%20tag%20commands).
These endpoints are not supported by the library yet but I'm currently working on implementing these. If this solves your problem please close this issue.

**Comment by FlorianHeigl** [comment]
closing already since the solution was direct passing of the dict. i didn't yet get around to write our stuff, but am sure it'll work.
will also ask for a 1.5 upgrade but since we moved into a different department's cmk, I suppose that will take a while :-)
